### PR TITLE
Update bootstrap-switch bower dependency to pull in minors and patche…

### PR DESCRIPTION
**Pull request by Zwartpet**
…s and update to 3.3.4

### CODE REVIEW

**Comment by Zwartpet** [comment]
Hi, the bootstrap-switch 3.3.2 is broken with jquery 3 on IE 11, they fixed this in 3.3.3. But your bower.json did not allow patches to update.

**Comment by Zwartpet** [comment]
Hi,

Fixed the broken tests, I (and the guy I am working for) would be pleased if you could merge or comment.

Kind regards,
Me

**Comment by Zwartpet** [comment]
Bump

**Comment by frekele** [comment]
@frapontillo ?

**Comment by Zwartpet** [comment]
@frapontillo Can you release a new version as well so I can update my project, I would rather not use the master branch.

**Comment by frapontillo** [comment]
@Zwartpet done! You now have version `0.5.2` available on both `bower` and `npm`.

**Pull request merged**
