### PR TITLE
Add support for indeterminate state

### PR DESCRIPTION
**Pull request by cjmaio**
Added support for an indeterminate state. Taking suggestions from the original PR, included tests, changed to 'undefined', ensured dist files were generated by grunt build, as well as testing with a Travis CI server.

### CODE REVIEW

**Comment by frapontillo** [comment]
@kubijo if you need the indeterminate state, just set the `ng-model`-bound object to `undefined`.

**Comment by kubijo** [comment]
I am sorry if I miss out something obvious, but angular seems to always cast undefined values to false. In practice my **ng-model** scope variable sure is typeof undefined, however the switch is set to false.

**Comment by frapontillo** [comment]
Can you please open a [new issue](https://github.com/frapontillo/angular-bootstrap-switch/issues/new)? Thanks.

**Comment by kubijo** [comment]
Sure

**Pull request closed without merging**
