### PR TITLE
fix(switchChange): wrap change eval in $timeout to force digest cycle

### PR DESCRIPTION
**Pull request by icholy**
Fixes `$digest` bug in #97

### CODE REVIEW

**Comment by frapontillo** [comment]
I went a long way to remove all $timeout calls some time ago. Could you please try and refactor it w/ `$evalAsync` or `$apply`?

**Comment by icholy** [comment]
@frapontillo  oh cool, I didn't know about `$evalAsync`

**Comment by icholy** [comment]
@frapontillo using `$apply` was the first thing I tried, but it throws an `error $digest already in progress` in the test.

**Comment by icholy** [comment]
Let me know if you want me to squash.

**Comment by frapontillo** [comment]
Squashed and merged into `develop` (4c5fcc1).
Thanks!

**Pull request closed without merging**
