### PR TITLE
Add commonjs package manager support (closes #82)

### LINKED ISSUE #82: Add commonjs package manager support
Can we add support for loading the bsSwitch as a CommonJS module?

See example of Angular UI-Router:
https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js

This will allow doing:

``` js
var bsSwitch = require('angular-bootstrap-switch');

angular.module('admin', [
    bsSwitch,
])
```

Instead of hard coding the module name.

### PR DESCRIPTION
**Pull request by alexilyaev**

### CODE REVIEW

**Comment by alexilyaev** [comment]
How come the build fails?

Running `grunt test-travis` passes ok.

**Comment by frapontillo** [comment]
I think some packages may need to be updated, could you please update all npm modules to their latest version? I mean actually changing the `package.json`, I don't know when I'll have some spare time for this.

**Comment by frapontillo** [comment]
@alexilyaev is this still needed? If so, could you please rebase and add at least some tests to guarantee that the CommonJS integration works?

Thanks.

**Comment by alexilyaev** [comment]
@frapontillo Hey, sorry, won't be able to get to it any time soon.

This is really a basic thing that all modern Angular modules are doing, now that ES6 and module loaders became a standard of development.

Please read my issue again, though `ui-router` updated their module to a Webpack build, it's the same principle (UMD pattern)
https://github.com/frapontillo/angular-bootstrap-switch/issues/82

I'd appreciate if you'd dig deeper into this and integrate it.
In a recent project, this is the only package that is still loaded with a manual name instead of `export`ing the name.

**Comment by frapontillo** [comment]
Me neither, I will soon move away from Web development so I don't think I will have the chance to work on it anymore.

Let's leave the issue open just in case anyone wants to work on it.

**Comment by frapontillo** [comment]
Leaving #82 open and closing this.

**Pull request closed without merging**
