### PR TITLE
chore(release): 0.5.0-alpha.1

### PR DESCRIPTION
**Pull request by icholy**
#80

### CODE REVIEW

**Comment by frapontillo** [comment]
I'd like to include #101 at least, then I'll cut a release.

**Comment by icholy** [comment]
@frapontillo ping?

**Comment by frapontillo** [comment]
Doing it today.

**Comment by frapontillo** [comment]
Closed via dffb8ba9e7d2da1ef7c8d8b5b76063923b983188.

**Comment by icholy** [comment]
@frapontillo `npm publish` pls.

**Comment by frapontillo** [comment]
@icholy sorry, I am too used to bower to remember that! Done! :+1:

**Comment by icholy** [comment]
@frapontillo sweet. I use bower too, just covering all the bases.

**Pull request closed without merging**
